{{- $previous := (lookup "v1" "Secret" .Release.Namespace (printf "%s-auth" (include "influxdb.fullname" . ))) }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "influxdb.labels" . | nindent 4 }}
  name: {{ template "influxdb.fullname" . }}-auth
data:
  {{- if .Values.adminUser.token }}
  admin-token: {{ .Values.adminUser.token  | b64enc | quote }}
  {{- else if $previous }}
  admin-token: {{ index $previous.data "admin-token" }}
  {{- else }}
  admin-token: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}

  {{- if .Values.adminUser.password }}
  admin-password: {{ .Values.adminUser.password | b64enc | quote }}
  {{- else if $previous }}
  admin-password: {{ index $previous.data "admin-password" }}
  {{- else }}
  admin-password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
